version: "3.4"

services:

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: nghia
      MYSQL_DATABASE: nghia
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user
      MYSQL_TCP_PORT: 3306
    logging:
      driver: none

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: nghia
    logging:
      driver: none
